/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include "qrunhist.h"

void  QRunHist::initDialog(){
  this->resize(540,400);
  this->setMinimumSize(0,0);
  QWidget_1= new QWidget(this,"NoName");
  QWidget_1->setGeometry(10,10,520,340);
  QWidget_1->setMinimumSize(0,0);
  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(220,360,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setText("&OK");
  QPushButton_1->setAutoDefault(true);

}
