/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <qtooltip.h>
#include "qprintoptions.h"

void  QPrintOptions::initDialog(){
  this->resize(440,330);
  this->setMinimumSize(0,0);
  btnOK= new QPushButton(this,"NoName");
  btnOK->setGeometry(220,280,100,30);
  btnOK->setMinimumSize(0,0);
  btnOK->setText("&OK");
  btnOK->setDefault(true);

  btnCancel= new QPushButton(this,"NoName");
  btnCancel->setGeometry(330,280,100,30);
  btnCancel->setMinimumSize(0,0);
  btnCancel->setText("&Cancel");

  chkbxPrintInColor= new QCheckBox(this,"NoName");
  chkbxPrintInColor->setGeometry(10,20,200,30);
  chkbxPrintInColor->setMinimumSize(0,0);
  QToolTip::add(chkbxPrintInColor,"Activate this to using current color palette in printer output,\nor desactivate it to using gray scale.");
  chkbxPrintInColor->setText("Print using color palette");

  chkbxPrintImage= new QCheckBox(this,"NoName");
  chkbxPrintImage->setGeometry(10,50,200,30);
  chkbxPrintImage->setMinimumSize(0,0);
  QToolTip::add(chkbxPrintImage,"Activate this to print camera image in printer output.");
  chkbxPrintImage->setText("Print camera image");
  chkbxPrintImage->setChecked(true);

  chkbxPrintStatistics= new QCheckBox(this,"NoName");
  chkbxPrintStatistics->setGeometry(10,80,200,30);
  chkbxPrintStatistics->setMinimumSize(0,0);
  QToolTip::add(chkbxPrintStatistics,"Activate this to print image parameters and statistics in printer output");
  chkbxPrintStatistics->setText("Print statistics");
  chkbxPrintStatistics->setChecked(true);

  chkbxPrintHistograms= new QCheckBox(this,"NoName");
  chkbxPrintHistograms->setGeometry(10,110,200,30);
  chkbxPrintHistograms->setMinimumSize(0,0);
  QToolTip::add(chkbxPrintHistograms,"Activate this to print histograms in printer output");
  chkbxPrintHistograms->setText("Print histograms");
  chkbxPrintHistograms->setChecked(true);

  btngrpOutput= new QButtonGroup(this,"NoName");
  btngrpOutput->setGeometry(240,20,190,150);
  btngrpOutput->setMinimumSize(0,0);
  btngrpOutput->setTitle(" Print output ");

  rbPrinterSetup= new QRadioButton(btngrpOutput,"NoName");
  rbPrinterSetup->setGeometry(10,20,100,30);
  rbPrinterSetup->setMinimumSize(0,0);
  QToolTip::add(rbPrinterSetup,"Shows printer dialog");
  rbPrinterSetup->setText("Setup dialog");
  rbPrinterSetup->setChecked(true);

  rbPrinterPrinter= new QRadioButton(btngrpOutput,"NoName");
  rbPrinterPrinter->setGeometry(10,50,130,30);
  rbPrinterPrinter->setMinimumSize(0,0);
  QToolTip::add(rbPrinterPrinter,"Send output directly to the default printer");
  rbPrinterPrinter->setText("Directly to printer");

  rbPrinterFile= new QRadioButton(btngrpOutput,"NoName");
  rbPrinterFile->setGeometry(10,80,100,30);
  rbPrinterFile->setMinimumSize(0,0);
  rbPrinterFile->setText("Print to files");

  rbPrinterFileAll= new QRadioButton(btngrpOutput,"NoName");
  rbPrinterFileAll->setGeometry(10,110,170,30);
  rbPrinterFileAll->setMinimumSize(0,0);
  QToolTip::add(rbPrinterFileAll,"Appends all the images to one single file");
  rbPrinterFileAll->setText("Everything to one file");

  lePrintCommand= new QLineEdit(this,"NoName");
  lePrintCommand->setGeometry(140,150,90,30);
  lePrintCommand->setMinimumSize(0,0);
  lePrintCommand->setText("lpr ");

  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,150,100,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText("Print command:");

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,190,130,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText("Multiple output prefix:");

  lePrintPrefix= new QLineEdit(this,"NoName");
  lePrintPrefix->setGeometry(140,190,90,30);
  lePrintPrefix->setMinimumSize(0,0);
  QToolTip::add(lePrintPrefix,"Prefix to be used when selecting 'Print to files'");
  lePrintPrefix->setText("/tmp/qd_");

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,230,120,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText("Output File:");

  lePrintFilename= new QLineEdit(this,"NoName");
  lePrintFilename->setGeometry(140,230,210,30);
  lePrintFilename->setMinimumSize(0,0);
  lePrintFilename->setText("/tmp/qd.ps");

  QPushButton_3= new QPushButton(this,"NoName");
  QPushButton_3->setGeometry(360,230,70,30);
  QPushButton_3->setMinimumSize(0,0);
  QPushButton_3->setText("Browse...");

}
